[package]
name = "thot"
version = "0.1.2"
edition = "2024"
license = "AGPL-3.0"
description = "An asm"
authors = ["Saigo Ekitae <saigoekitae@gmail.com>"]
repository = "https://github.com/hackia/thot"
categories = ["compilers"]
[dependencies]
blake3 = "1.8.3"
clap = "4.5.59"
